### ISSUE TITLE
Not Support In typescript file

### ISSUE THREAD

**Issue by boswellgao** [brillout/vite-plugin-mdx#27]
in index.tsx
```javascript
import Readme from './Readme.mdx'
```
and the lint told me 
```javascript
Cannot find module './Readme.mdx' or its corresponding type declarations.ts(2307)
```

**Comment by silvenon** [comment]
Could you share more about your setup? Your Vite configuration, project structure, or ideally steps to reproduce the error.

**Comment by boswellgao** [comment]
@silvenon Thank you for your reply

here you can get the project 

https://github.com/boswellgao/vite-react-live-preview

**Comment by silvenon** [comment]
The problem is with TypeScript, not `vite-plugin-mdx`. Vite only compiles away TypeScript, it doesn't do any type checking. One way to solve your problem is to add a common type definition for all your `*.mdx` files:

```ts
declare module '*.mdx' {
  let MDXComponent: (props: Record<string, unknown>) => JSX.Element
  export default MDXComponent
}
```

If you need to be more specific about a particular `*.mdx`, add a `.d.ts` file with the same name.

**Comment by boswellgao** [comment]
@silvenon  Thanks. you are right,it's typescript proplem
[TypeScript support for .mdx file extensions](https://github.com/microsoft/TypeScript/issues/36440)
